# Archie-specific autostart
# Launch spotify into the scratchpad on login

# Window rules: send to scratchpad silently (don't switch to it)
windowrule = workspace special:scratchpad silent, match:class ^(spotify)$
#windowrule = workspace special:scratchpad silent, match:title ^(WhatsApp)

# Autostart
exec-once = uwsm app -- spotify
#exec-once = uwsm app -- chromium --new-window --ozone-platform=wayland --app="https://web.whatsapp.com/"
